#!/bin/bash
export EPICS_CA_MAX_ARRAY_BYTES=360100200
cd /corvette/home/epics/support/CARS/iocBoot/ioc13Eiger2_9M
#/corvette/home/epics/support/areaDetector/ADEiger/iocs/eigerIOC/bin/linux-x86_64/eigerDetectorApp st.cmd
/corvette/home/epics/devel/areaDetector/ADEiger/iocs/eigerIOC/bin/linux-x86_64/eigerDetectorApp st.cmd

