#!/bin/sh
#medm -x -macro "P=13MARCCD_IMCA:, R=cam1:" marCCD.adl &
cd /home/epics/support/CARS/iocBoot/ioc13marCCD3
/home/epics/support/areaDetector/ADmarCCD/iocs/marCCDIOC/bin/linux-x86/marCCDApp st.cmd

