#!/bin/bash
cd /corvette/home/epics/support/CARS/iocBoot/ioc13idb_pg1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/corvette/home/epics/support/areaDetector/ADPointGrey/lib/linux-x86_64
/corvette/home/epics/support/areaDetector/ADPointGrey/iocs/pointGreyIOC/bin/linux-x86_64/pointGreyApp st.cmd

