#!/bin/sh

cd /home/epics/support/CARS/iocBoot/ioc13Keithley1

PORT=20051
LOGFILE=/home/epics/logs/iocKeithley1.log

PROCSERV=/usr/local/bin/procServ

$PROCSERV --noautorestart -n "Keithley1" -i ^D -L $LOGFILE $PORT ../../bin/linux-x86/CARSApp st.cmd
telnet localhost $PORT


