# Create 11 statistics plugins
NDStatsConfigure("$(PORT)_STATS1", $(QSIZE), 0, "$(PORT)", 0, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):Current1:, PORT=$(PORT)_STATS1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS2", $(QSIZE), 0, "$(PORT)", 1, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):Current2:, PORT=$(PORT)_STATS2,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS3", $(QSIZE), 0, "$(PORT)", 2, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):Current3:, PORT=$(PORT)_STATS3,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS4", $(QSIZE), 0, "$(PORT)", 3, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):Current4:, PORT=$(PORT)_STATS4,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS5", $(QSIZE), 0, "$(PORT)", 4, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):SumX:,    PORT=$(PORT)_STATS5,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS6", $(QSIZE), 0, "$(PORT)", 5, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):SumY:,    PORT=$(PORT)_STATS6,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS7", $(QSIZE), 0, "$(PORT)", 6, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):SumAll:,  PORT=$(PORT)_STATS7,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS8", $(QSIZE), 0, "$(PORT)", 7, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):DiffX:,   PORT=$(PORT)_STATS8,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS9", $(QSIZE), 0, "$(PORT)", 8, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):DiffY:,   PORT=$(PORT)_STATS9,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS10",$(QSIZE), 0, "$(PORT)", 9, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):PosX:,   PORT=$(PORT)_STATS10,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")
NDStatsConfigure("$(PORT)_STATS11",$(QSIZE), 0, "$(PORT)", 10, 0, 0)
dbLoadRecords("$(ADCORE)/db/NDStats.template",     "P=$(PREFIX),R=$(PORT):PosY:,   PORT=$(PORT)_STATS11,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),HIST_SIZE=256,XSIZE=$(RING_SIZE),YSIZE=0,NCHANS=$(TSPOINTS)")

# Create a netCDF file saving plugin.
NDFileNetCDFConfigure("$(PORT)_FileNetCDF1", $(QSIZE), 0, "$(PORT)", 11)
dbLoadRecords("$(ADCORE)/db/NDFileNetCDF.template","P=$(PREFIX),R=$(PORT):netCDF1:,PORT=$(PORT)_FileNetCDF1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT)")

# This creates a waveform large enough for 11x10000 arrays.
NDStdArraysConfigure("$(PORT)_Image1", $(QSIZE), 0, "$(PORT)", 11)
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=$(PORT):image1:,PORT=$(PORT)_Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),TYPE=Float64,FTVL=DOUBLE,NELEMENTS=110000")
