#!/bin/bash
cd /corvette/home/epics/support/CARS/iocBoot/ioc13bma_pg1
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/corvette/home/epics/support/areaDetector/ADSpinnaker/lib/linux-x86_64
/corvette/home/epics/support/areaDetector/ADSpinnaker/iocs/spinnakerIOC/bin/linux-x86_64/spinnakerApp st.cmd

