TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = cygwin-x86
ARCH = win32-x86-static
#ARCH = linux-x86
#ARCH = linux-x86_64
#ARCH = linux-x86
#ARCH = linux-x86_64
TARGETS = envPaths dllPath.bat
include $(TOP)/configure/RULES.ioc
