13BMA:m1.DHLM       50.0000
13BMA:m1.DLLM       0.00000
13BMA:m1.TWV      0.100000
13BMA:m1.DISA        0
13BMA:m1.DISP    0
13BMA:m1:scanParms.SP        0.0000000
13BMA:m1:scanParms.EP        0.0000000
13BMA:m1:scanParms.NP        2
13BMA:m1_able.VAL        0
13BMA:m2.DHLM       50.0000
13BMA:m2.DLLM       0.00000
13BMA:m2.TWV      0.100000
13BMA:m2.DISA        0
13BMA:m2.DISP    0
13BMA:m2:scanParms.SP        0.0000000
13BMA:m2:scanParms.EP        0.0000000
13BMA:m2:scanParms.NP        2
13BMA:m2_able.VAL        0
13BMA:m3.DHLM       50.0000
13BMA:m3.DLLM      -4.00000
13BMA:m3.TWV      0.100000
13BMA:m3.DISA        0
13BMA:m3.DISP    0
13BMA:m3:scanParms.SP        0.0000000
13BMA:m3:scanParms.EP        0.0000000
13BMA:m3:scanParms.NP        2
13BMA:m3_able.VAL        0
13BMA:m4.DHLM       50.0000
13BMA:m4.DLLM      -4.00000
13BMA:m4.TWV      0.100000
13BMA:m4.DISA        0
13BMA:m4.DISP    0
13BMA:m4:scanParms.SP        0.0000000
13BMA:m4:scanParms.EP        0.0000000
13BMA:m4:scanParms.NP        2
13BMA:m4_able.VAL        0
13BMA:m5.DHLM   1.00000e+06
13BMA:m5.DLLM  -1.00000e+06
13BMA:m5.TWV       1.00000
13BMA:m5.DISA        0
13BMA:m5.DISP    0
13BMA:m5:scanParms.SP        0.0000000
13BMA:m5:scanParms.EP        0.0000000
13BMA:m5:scanParms.NP        2
13BMA:m5_able.VAL        0
13BMA:m6.DHLM   1.00000e+06
13BMA:m6.DLLM  -1.00000e+06
13BMA:m6.TWV       1.00000
13BMA:m6.DISA        0
13BMA:m6.DISP    0
13BMA:m6:scanParms.SP        0.0000000
13BMA:m6:scanParms.EP        0.0000000
13BMA:m6:scanParms.NP        2
13BMA:m6_able.VAL        0
13BMA:m7.DHLM   1.00000e+06
13BMA:m7.DLLM  -1.00000e+06
13BMA:m7.TWV       1.00000
13BMA:m7.DISA        0
13BMA:m7.DISP    0
13BMA:m7:scanParms.SP        0.0000000
13BMA:m7:scanParms.EP        0.0000000
13BMA:m7:scanParms.NP        2
13BMA:m7_able.VAL        0
13BMA:m8.DHLM   1.00000e+06
13BMA:m8.DLLM  -1.00000e+06
13BMA:m8.TWV       1.00000
13BMA:m8.DISA        0
13BMA:m8.DISP    0
13BMA:m8:scanParms.SP        0.0000000
13BMA:m8:scanParms.EP        0.0000000
13BMA:m8:scanParms.NP        2
13BMA:m8_able.VAL        0
13BMA:m9.DHLM       500.000
13BMA:m9.DLLM      -500.000
13BMA:m9.TWV    0.01000000
13BMA:m9.DISA        0
13BMA:m9.DISP    0
13BMA:m9:scanParms.SP       -1.0000000
13BMA:m9:scanParms.EP        1.0000000
13BMA:m9:scanParms.NP       21
13BMA:m9_able.VAL        0
13BMA:scan1.NPTS      100
13BMA:scan1.PASM        0
13BMA:scan1.SCAN        0
13BMA:scan1.BSPV 
13BMA:scan1.ASPV 
13BMA:scan1.T1PV 13BMA:scaler1.CNT
13BMA:scan1.T2PV 
13BMA:scan1.D1PV 13BMA:scaler1.T
13BMA:scan1.D2PV 13BMA:scaler1.S2
13BMA:scan1.D3PV 13BMA:scaler1.S3
13BMA:scan1.D4PV 13BMA:scaler1.S4
13BMA:scan1.D5PV 
13BMA:scan1.D6PV 
13BMA:scan1.D7PV 
13BMA:scan1.D8PV 
13BMA:scan1.D9PV 
13BMA:scan1.DAPV 
13BMA:scan1.DBPV 
13BMA:scan1.DCPV 
13BMA:scan1.DDPV 
13BMA:scan1.DEPV 
13BMA:scan1.DFPV 
13BMA:scan1.P1PV 
13BMA:scan1.P2PV 
13BMA:scan1.P3PV 
13BMA:scan1.P4PV 
13BMA:scan1.R1PV 
13BMA:scan1.R2PV 
13BMA:scan1.R3PV 
13BMA:scan1.R4PV 
13BMA:scan1.P1SM        0
13BMA:scan1.P2SM        0
13BMA:scan1.P3SM        0
13BMA:scan1.P4SM        0
13BMA:scan1.P1SP        0.0000000
13BMA:scan1.P2SP        0.0000000
13BMA:scan1.P3SP        0.0000000
13BMA:scan1.P4SP        0.0000000
13BMA:scan1.P1EP        0.0000000
13BMA:scan1.P2EP        0.0000000
13BMA:scan1.P3EP        0.0000000
13BMA:scan1.P4EP        0.0000000
13BMA:scan1.P1AR        0
13BMA:scan1.P2AR        0
13BMA:scan1.P3AR        0
13BMA:scan1.P4AR        0
13BMA:scan2.NPTS      100
13BMA:scan2.PASM        0
13BMA:scan2.SCAN        0
13BMA:scan2.BSPV 
13BMA:scan2.ASPV 
13BMA:scan2.T1PV 13BMA:scan1.EXSC
13BMA:scan2.T2PV 
13BMA:scan2.D1PV 
13BMA:scan2.D2PV 
13BMA:scan2.D3PV 
13BMA:scan2.D4PV 
13BMA:scan2.D5PV 
13BMA:scan2.D6PV 
13BMA:scan2.D7PV 
13BMA:scan2.D8PV 
13BMA:scan2.D9PV 
13BMA:scan2.DAPV 
13BMA:scan2.DBPV 
13BMA:scan2.DCPV 
13BMA:scan2.DDPV 
13BMA:scan2.DEPV 
13BMA:scan2.DFPV 
13BMA:scan2.P1PV 
13BMA:scan2.P2PV 
13BMA:scan2.P3PV 
13BMA:scan2.P4PV 
13BMA:scan2.R1PV 
13BMA:scan2.R2PV 
13BMA:scan2.R3PV 
13BMA:scan2.R4PV 
13BMA:scan2.P1SM        0
13BMA:scan2.P2SM        0
13BMA:scan2.P3SM        0
13BMA:scan2.P4SM        0
13BMA:scan2.P1SP        0.0000000
13BMA:scan2.P2SP        0.0000000
13BMA:scan2.P3SP        0.0000000
13BMA:scan2.P4SP        0.0000000
13BMA:scan2.P1EP        0.0000000
13BMA:scan2.P2EP        0.0000000
13BMA:scan2.P3EP        0.0000000
13BMA:scan2.P4EP        0.0000000
13BMA:scan2.P1AR        0
13BMA:scan2.P2AR        0
13BMA:scan2.P3AR        0
13BMA:scan2.P4AR        0
13BMA:scan3.NPTS       10
13BMA:scan3.PASM        0
13BMA:scan3.SCAN        0
13BMA:scan3.BSPV 
13BMA:scan3.ASPV 
13BMA:scan3.T1PV 13BMA:scan2.EXSC
13BMA:scan3.T2PV 
13BMA:scan3.D1PV 
13BMA:scan3.D2PV 
13BMA:scan3.D3PV 
13BMA:scan3.D4PV 
13BMA:scan3.D5PV 
13BMA:scan3.D6PV 
13BMA:scan3.D7PV 
13BMA:scan3.D8PV 
13BMA:scan3.D9PV 
13BMA:scan3.DAPV 
13BMA:scan3.DBPV 
13BMA:scan3.DCPV 
13BMA:scan3.DDPV 
13BMA:scan3.DEPV 
13BMA:scan3.DFPV 
13BMA:scan3.P1PV 
13BMA:scan3.P2PV 
13BMA:scan3.P3PV 
13BMA:scan3.P4PV 
13BMA:scan3.R1PV 
13BMA:scan3.R2PV 
13BMA:scan3.R3PV 
13BMA:scan3.R4PV 
13BMA:scan3.P1SM        0
13BMA:scan3.P2SM        0
13BMA:scan3.P3SM        0
13BMA:scan3.P4SM        0
13BMA:scan3.P1SP        0.0000000
13BMA:scan3.P2SP        0.0000000
13BMA:scan3.P3SP        0.0000000
13BMA:scan3.P4SP        0.0000000
13BMA:scan3.P1EP        0.0000000
13BMA:scan3.P2EP        0.0000000
13BMA:scan3.P3EP        0.0000000
13BMA:scan3.P4EP        0.0000000
13BMA:scan3.P1AR        0
13BMA:scan3.P2AR        0
13BMA:scan3.P3AR        0
13BMA:scan3.P4AR        0
13BMA:scan4.NPTS       10
13BMA:scan4.PASM        0
13BMA:scan4.SCAN        0
13BMA:scan4.BSPV 
13BMA:scan4.ASPV 
13BMA:scan4.T1PV 13BMA:scan3.EXSC
13BMA:scan4.T2PV 
13BMA:scan4.D1PV 
13BMA:scan4.D2PV 
13BMA:scan4.D3PV 
13BMA:scan4.D4PV 
13BMA:scan4.D5PV 
13BMA:scan4.D6PV 
13BMA:scan4.D7PV 
13BMA:scan4.D8PV 
13BMA:scan4.D9PV 
13BMA:scan4.DAPV 
13BMA:scan4.DBPV 
13BMA:scan4.DCPV 
13BMA:scan4.DDPV 
13BMA:scan4.DEPV 
13BMA:scan4.DFPV 
13BMA:scan4.P1PV 
13BMA:scan4.P2PV 
13BMA:scan4.P3PV 
13BMA:scan4.P4PV 
13BMA:scan4.R1PV 
13BMA:scan4.R2PV 
13BMA:scan4.R3PV 
13BMA:scan4.R4PV 
13BMA:scan4.P1SM        0
13BMA:scan4.P2SM        0
13BMA:scan4.P3SM        0
13BMA:scan4.P4SM        0
13BMA:scan4.P1SP        0.0000000
13BMA:scan4.P2SP        0.0000000
13BMA:scan4.P3SP        0.0000000
13BMA:scan4.P4SP        0.0000000
13BMA:scan4.P1EP        0.0000000
13BMA:scan4.P2EP        0.0000000
13BMA:scan4.P3EP        0.0000000
13BMA:scan4.P4EP        0.0000000
13BMA:scan4.P1AR        0
13BMA:scan4.P2AR        0
13BMA:scan4.P3AR        0
13BMA:scan4.P4AR        0
13BMA:1D_pDummySeq.DLY2      0.020000000
13BMA:2D_pDummySeq.DLY2      0.020000000
13BMA:3D_pDummySeq.DLY2      0.020000000
